; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

; Librerías requeridas por el proyecto
lib_deps =
    arduino-libraries/Servo @ ^1.1.8          ; Para control de Servos
    arduino-libraries/Wire @ ^1.0             ; Para comunicación I2C
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4  ; Para el LCD I2C
    adafruit/Adafruit ADS1X15 @ ^2.4.0      ; Para el conversor ADC ADS1115
    bogde/HX711 @ ^0.7.5  ; Para el sensor de peso HX711
    ; EEPROM usualmente viene incluida con el framework Arduino para AVR

; Opcional: Añadir flags de compilador para más warnings
; build_flags = -Wall